
type MemberPayload = {
    memberId: number,
    approvedCount: number,
    approvalState: number,
    waliEmailAddressConfirmed: number,
    emailAddressConfirmed: number,
    phoneNumberConfirmed: number,
    photosApproved: number,
    pushNotifications: number,
    nickname?: string,
    gender?: string,
    emailAddress?: string,
    phoneNumber?: number,
    fbId?: string,
    udid?: string,
    passwordToken?: string,
    profileCreated?: number,
    deviceOs?: string,
    approved?: number,
    activeProfile?: number,
    devicePushToken?: string,
    awsendpointArn?: string,
    premium?: number,
    premiumStarted?: string,
    premiumExpires?: string,
    premiumProductSuffix?: string,
    hashMemberId?: string,
    lastActiveTimeStamp?: string,
    timeStampRegistered?: string,
    timeStampCreatedProfile?: string,
    timeStampCompletedProfile?: string,
    consentedAtTimeStamp?: string,
    idfa?: string,
    oldPhoneNumber?: number,
    oldEmailAddress?: string,
    sect?: string,
    maritalStatus?: string,
    profession?: number,
    ethnicOrigin?: number,
    photoOne?: string,
    photoTwo?: string,
    photoThree?: string,
    photoFour?: string,
    photoFive?: string,
    photoVerification?: string,
    photoOneBlurred?: string,
    photoTwoBlurred?: string,
    photoThreeBlurred?: string,
    photoFourBlurred?: string,
    photoFiveBlurred?: string,
    publicPhotos?: number,
    timeStamp?: string,
    prayerLevel?: number,
    practisingLevel?: number,
    waliEmailAddress?: string,
    country?: number,
    admin?: number,
    dobDay?: number,
    dobMonth?: number,
    dobYear?: number,
    height?: number,
    islamicDress?: string,
    discoverable?: number,
    permanentlyBlocked?: number,
    banExpires?: string,
    appVersion?: string,
    deletedAccountReason?: string,
    deviceModel?: string,
    deviceVersion?: string,
    gpslongitude?: number,
    gpslatitude?: number,
    gpsderivedLocation?: number,
    gpsderivedCountry?: number,
    gpsderivedTimezone?: string,
    serverRemoteAddr?: string,
    httpXForwardedFor?: string,
    ipAddressCountryCode?: string,
    iplatitude?: number,
    iplongitude?: number,
    ipderivedLocation?: number,
    ipderivedCountry?: number,
    ipderivedTimezone?: string,
    languages?: string,
    locale?: string,
    httpAcceptLanguage?: string,
    countryFromSim?: number,
    countryFromDeviceLocale?: number,
    timezoneFromPhone?: string,
    sendAdminBlastPushNotifications?: number,
    education?: string,
    jobTitle?: string,
    companyOfEmployment?: string,
    onlyEatHalal?: number,
    drinkAlcohol?: number,
    revert?: number,
    smoker?: number,
    marriageHorizon?: number,
    citizenshipCountry?: number,
    ethnicityGrouping?: number,
    willingToRelocateNationally?: number,
    willingToRelocateAbroad?: number,
    statusMessage?: string,
    longDescription?: string,
    profileReviewedByAdmin?: number,
    adminProfileReviewComment?: string,
    children?: number,
    promptPostRegistration?: number,
    emailConfirmationPincode?: number,
    timeStampNicknameLastUpdated?: string,
    timeStampDoblastUpdated?: string,
    timeStampGenderLastUpdated?: string,
    jailbrokenDevice?: number,
    emailNotifications?: number,
    emailReengagement?: number,
    emailMarketing?: number,
    fbEmailAddress?: string,
    instantMatchCredit?: number,
    referrerInviteCode?: string,
    referrerMemberId?: number,
    badgeCount?: number,
    hideAds?: number,
    hidePremiumBadge?: number,
    refSource?: string,
    refMedium?: string,
    refCampaign?: string,
    refTerm?: string,
    refContent?: string,
    timeStampFirstInstalled?: string,
    deleteAfterTimeStamp?: string
}

export default class Member 
{
    private constructor(
        public memberId: number,
        public approvedCount: number,
        public approvalState: number,
        public waliEmailAddressConfirmed: number,
        public emailAddressConfirmed: number,
        public phoneNumberConfirmed: number,
        public photosApproved: number,
        public pushNotifications: number,
        public nickname?: string,
        public gender?: string,
        public emailAddress?: string,
        public phoneNumber?: number,
        public fbId?: string,
        public udid?: string,
        public passwordToken?: string,
        public profileCreated?: number,
        public deviceOs?: string,
        public approved?: number,
        public activeProfile?: number,
        public devicePushToken?: string,
        public awsendpointArn?: string,
        public premium?: number,
        public premiumStarted?: string,
        public premiumExpires?: string,
        public premiumProductSuffix?: string,
        public hashMemberId?: string,
        public lastActiveTimeStamp?: string,
        public timeStampRegistered?: string,
        public timeStampCreatedProfile?: string,
        public timeStampCompletedProfile?: string,
        public consentedAtTimeStamp?: string,
        public idfa?: string,
        public oldPhoneNumber?: number,
        public oldEmailAddress?: string,
        public sect?: string,
        public maritalStatus?: string,
        public profession?: number,
        public ethnicOrigin?: number,
        public photoOne?: string,
        public photoTwo?: string,
        public photoThree?: string,
        public photoFour?: string,
        public photoFive?: string,
        public photoVerification?: string,
        public photoOneBlurred?: string,
        public photoTwoBlurred?: string,
        public photoThreeBlurred?: string,
        public photoFourBlurred?: string,
        public photoFiveBlurred?: string,
        public publicPhotos?: number,
        public timeStamp?: string,
        public prayerLevel?: number,
        public practisingLevel?: number,
        public waliEmailAddress?: string,
        public country?: number,
        public admin?: number,
        public dobDay?: number,
        public dobMonth?: number,
        public dobYear?: number,
        public height?: number,
        public islamicDress?: string,
        public discoverable?: number,
        public permanentlyBlocked?: number,
        public banExpires?: string,
        public appVersion?: string,
        public deletedAccountReason?: string,
        public deviceModel?: string,
        public deviceVersion?: string,
        public gpslongitude?: number,
        public gpslatitude?: number,
        public gpsderivedLocation?: number,
        public gpsderivedCountry?: number,
        public gpsderivedTimezone?: string,
        public serverRemoteAddr?: string,
        public httpXForwardedFor?: string,
        public ipAddressCountryCode?: string,
        public iplatitude?: number,
        public iplongitude?: number,
        public ipderivedLocation?: number,
        public ipderivedCountry?: number,
        public ipderivedTimezone?: string,
        public languages?: string,
        public locale?: string,
        public httpAcceptLanguage?: string,
        public countryFromSim?: number,
        public countryFromDeviceLocale?: number,
        public timezoneFromPhone?: string,
        public sendAdminBlastPushNotifications?: number,
        public education?: string,
        public jobTitle?: string,
        public companyOfEmployment?: string,
        public onlyEatHalal?: number,
        public drinkAlcohol?: number,
        public revert?: number,
        public smoker?: number,
        public marriageHorizon?: number,
        public citizenshipCountry?: number,
        public ethnicityGrouping?: number,
        public willingToRelocateNationally?: number,
        public willingToRelocateAbroad?: number,
        public statusMessage?: string,
        public longDescription?: string,
        public profileReviewedByAdmin?: number,
        public adminProfileReviewComment?: string,
        public children?: number,
        public promptPostRegistration?: number,
        public emailConfirmationPincode?: number,
        public timeStampNicknameLastUpdated?: string,
        public timeStampDoblastUpdated?: string,
        public timeStampGenderLastUpdated?: string,
        public jailbrokenDevice?: number,
        public emailNotifications?: number,
        public emailReengagement?: number,
        public emailMarketing?: number,
        public fbEmailAddress?: string,
        public instantMatchCredit?: number,
        public referrerInviteCode?: string,
        public referrerMemberId?: number,
        public badgeCount?: number,
        public hideAds?: number,
        public hidePremiumBadge?: number,
        public refSource?: string,
        public refMedium?: string,
        public refCampaign?: string,
        public refTerm?: string,
        public refContent?: string,
        public timeStampFirstInstalled?: string,
        public deleteAfterTimeStamp?: string) 
    {
        //
    }

    static build(payload: MemberPayload) 
    {
        return new Member(
            payload.memberId,
            payload.approvedCount,
            payload.approvalState,
            payload.waliEmailAddressConfirmed,
            payload.emailAddressConfirmed,
            payload.phoneNumberConfirmed,
            payload.photosApproved,
            payload.pushNotifications,
            payload.nickname,
            payload.gender,
            payload.emailAddress,
            payload.phoneNumber,
            payload.fbId,
            payload.udid,
            payload.passwordToken,
            payload.profileCreated,
            payload.deviceOs,
            payload.approved,
            payload.activeProfile,
            payload.devicePushToken,
            payload.awsendpointArn,
            payload.premium,
            payload.premiumStarted,
            payload.premiumExpires,
            payload.premiumProductSuffix,
            payload.hashMemberId,
            payload.lastActiveTimeStamp,
            payload.timeStampRegistered,
            payload.timeStampCreatedProfile,
            payload.timeStampCompletedProfile,
            payload.consentedAtTimeStamp,
            payload.idfa,
            payload.oldPhoneNumber,
            payload.oldEmailAddress,
            payload.sect,
            payload.maritalStatus,
            payload.profession,
            payload.ethnicOrigin,
            payload.photoOne,
            payload.photoTwo,
            payload.photoThree,
            payload.photoFour,
            payload.photoFive,
            payload.photoVerification,
            payload.photoOneBlurred,
            payload.photoTwoBlurred,
            payload.photoThreeBlurred,
            payload.photoFourBlurred,
            payload.photoFiveBlurred,
            payload.publicPhotos,
            payload.timeStamp,
            payload.prayerLevel,
            payload.practisingLevel,
            payload.waliEmailAddress,
            payload.country,
            payload.admin,
            payload.dobDay,
            payload.dobMonth,
            payload.dobYear,
            payload.height,
            payload.islamicDress,
            payload.discoverable,
            payload.permanentlyBlocked,
            payload.banExpires,
            payload.appVersion,
            payload.deletedAccountReason,
            payload.deviceModel,
            payload.deviceVersion,
            payload.gpslongitude,
            payload.gpslatitude,
            payload.gpsderivedLocation,
            payload.gpsderivedCountry,
            payload.gpsderivedTimezone,
            payload.serverRemoteAddr,
            payload.httpXForwardedFor,
            payload.ipAddressCountryCode,
            payload.iplatitude,
            payload.iplongitude,
            payload.ipderivedLocation,
            payload.ipderivedCountry,
            payload.ipderivedTimezone,
            payload.languages,
            payload.locale,
            payload.httpAcceptLanguage,
            payload.countryFromSim,
            payload.countryFromDeviceLocale,
            payload.timezoneFromPhone,
            payload.sendAdminBlastPushNotifications,
            payload.education,
            payload.jobTitle,
            payload.companyOfEmployment,
            payload.onlyEatHalal,
            payload.drinkAlcohol,
            payload.revert,
            payload.smoker,
            payload.marriageHorizon,
            payload.citizenshipCountry,
            payload.ethnicityGrouping,
            payload.willingToRelocateNationally,
            payload.willingToRelocateAbroad,
            payload.statusMessage,
            payload.longDescription,
            payload.profileReviewedByAdmin,
            payload.adminProfileReviewComment,
            payload.children,
            payload.promptPostRegistration,
            payload.emailConfirmationPincode,
            payload.timeStampNicknameLastUpdated,
            payload.timeStampDoblastUpdated,
            payload.timeStampGenderLastUpdated,
            payload.jailbrokenDevice,
            payload.emailNotifications,
            payload.emailReengagement,
            payload.emailMarketing,
            payload.fbEmailAddress,
            payload.instantMatchCredit,
            payload.referrerInviteCode,
            payload.referrerMemberId,
            payload.badgeCount,
            payload.hideAds,
            payload.hidePremiumBadge,
            payload.refSource,
            payload.refMedium,
            payload.refCampaign,
            payload.refTerm,
            payload.refContent,
            payload.timeStampFirstInstalled,
            payload.deleteAfterTimeStamp
        )
    }
}